FROM python:3-alpine

USER root
RUN adduser -D -s /bin/nologin -h /app aqua
ADD . /app
WORKDIR /app
RUN chown -R aqua:aqua /app
RUN apk add gcc g++ musl-dev libffi-dev \
        mariadb-connector-c-dev zlib-dev \
        libjpeg-turbo-dev
RUN ln -s /usr/local/bin/python3 /usr/bin/python3
USER aqua


RUN python3 -m venv /app/venv

RUN /app/venv/bin/pip3 install wheel
RUN /app/venv/bin/pip3 install -r requirements.txt
RUN if [ -d migrations/ ]; then rm -rf migrations/; fi
RUN /app/venv/bin/python3 manage.py db init
RUN /app/venv/bin/python3 manage.py db migrate
RUN /app/venv/bin/python3 manage.py create_db

RUN /app/venv/bin/pip3 install waitress

USER root
RUN apk del gcc g++ musl-dev libffi-dev \
        zlib-dev libjpeg-turbo-dev
RUN mv /app/docker/entrypoint.sh /
RUN rm -rf /app/docker/
USER aqua

CMD /entrypoint.sh
#CMD /app/venv/bin/waitress-serve --listen=0.0.0.0:5000 \
#                                          main.server:app
